/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "cmsis_os.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include <string.h>
#include "FreeRTOS_CLI.h"
#include "FreeRTOS_IO.h"
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
osThreadId defaultTaskHandle;
/* USER CODE BEGIN PV */
volatile uint32_t counter = 0;
SemaphoreHandle_t sem = NULL;
//SemaphoreHandle_t sem_rx = NULL;
QueueHandle_t queue_rx;
QueueHandle_t queue_keyb;
SemaphoreHandle_t mutex = NULL;
TimerHandle_t debounce;
/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
void StartDefaultTask(void const * argument);

/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */
typedef struct led_t_ {
	GPIO_TypeDef 	*led_port;
	uint16_t 		led_pin;
	TickType_t 		led_toggle_time;
}led_t;


void pisca_led(void *param){
	led_t *led = (led_t *)param;
	TickType_t timer;
	while(1){
		timer = xTaskGetTickCount();
		HAL_GPIO_TogglePin(led->led_port, led->led_pin);
		vTaskDelayUntil(&timer,led->led_toggle_time);
	}
}

#if 0
void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart){
	BaseType_t pxHigherPriorityTaskWoken = pdFALSE;
	xSemaphoreGiveFromISR(sem, &pxHigherPriorityTaskWoken);
	portYIELD_FROM_ISR(pxHigherPriorityTaskWoken);
}
#endif

volatile uint32_t cnt1 = 0;
void envia_serial_1(void *param){
	char *texto = "Olá mundo da tarefa 1!\n\r";
	uint32_t len = strlen(texto);
	while(1){
		if (xSemaphoreTake(mutex, 100) == pdTRUE){
			if (HAL_UART_Transmit_IT(&hlpuart1, (uint8_t *)texto, len) == HAL_OK){
				xSemaphoreTake(sem, portMAX_DELAY);
				cnt1++;
			}
			xSemaphoreGive(mutex);
		}
		taskYIELD();
	}
}

volatile uint32_t cnt2 = 0;
void envia_serial_2(void *param){
	char *texto = "Olá mundo da tarefa 2!\n\r";
	uint32_t len = strlen(texto);
	while(1){
		if (xSemaphoreTake(mutex, 100) == pdTRUE){
			if (HAL_UART_Transmit_IT(&hlpuart1, (uint8_t *)texto, len) == HAL_OK){
				xSemaphoreTake(sem, portMAX_DELAY);
				cnt2++;
			}
			xSemaphoreGive(mutex);
		}
		taskYIELD();
	}
}

void transmite_uart(uint8_t *string, uint32_t len){
	if (xSemaphoreTake(mutex, 100) == pdTRUE){
		if (HAL_UART_Transmit_IT(&hlpuart1, string, len) == HAL_OK){
			xSemaphoreTake(sem, portMAX_DELAY);
		}
		xSemaphoreGive(mutex);
	}
}

#if 0
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart){
	BaseType_t pxHigherPriorityTaskWoken = pdFALSE;
	xQueueSendToBackFromISR(queue_rx, huart->pRxBuffPtr, &pxHigherPriorityTaskWoken);
	portYIELD_FROM_ISR(pxHigherPriorityTaskWoken);
}
#endif

void receive_uart(uint8_t *data){
	xQueueReceive(queue_rx, data, portMAX_DELAY);
}

static BaseType_t prvTaskStatsCommand( char *pcWriteBuffer,
                                          size_t xWriteBufferLen,
										  const char *pcCommandString )
{
    static BaseType_t state = 0;

    if (!state){
        /* For simplicity, this function assumes the output buffer is large enough
        to hold all the text generated by executing the vTaskList() API function,
        so the xWriteBufferLen parameter is not used. */
        char *head = "Name		State  Priority  Stack  Number\n\r";
        ( void ) xWriteBufferLen;

        /* pcWriteBuffer is used directly as the vTaskList() parameter, so the table
        generated by executing vTaskList() is written directly into the output
        buffer. */
        strcpy(pcWriteBuffer, head);
        vTaskList( &pcWriteBuffer[strlen(head)]);

        /* The entire table was written directly to the output buffer.  Execution
        of this command is complete, so return pdFALSE. */
        state = 1;
        return pdTRUE;
    }else{
        state = 0;
        strcpy(pcWriteBuffer, "\n\r");
        return pdFALSE;
    }
}

static BaseType_t prvClearCommand( char *pcWriteBuffer,
                                          size_t xWriteBufferLen,
										  const char *pcCommandString )
{

	strcpy(pcWriteBuffer, "\033c");
	return false;

}

static const CLI_Command_Definition_t xClearCommand =
{
    "clear",
	"clear: Clear the console terminal\r\n\r\n",
	prvClearCommand,
    0
};



static const CLI_Command_Definition_t xTasksCommand =
{
    "tasks",
	"tasks: Lists all the installed tasks\r\n\r\n",
	prvTaskStatsCommand,
    0
};

#define MAX_INPUT_LENGTH    64
#define MAX_OUTPUT_LENGTH   512
static void shell_task(void *param){
	char cRxedChar;
	BaseType_t cInputIndex = 0;
	BaseType_t xMoreDataToFollow;
	/* The input and output buffers are declared static to keep them off the stack. */
	static char pcOutputString[ MAX_OUTPUT_LENGTH ], pcInputString[ MAX_INPUT_LENGTH ];

	Peripheral_Descriptor_t lpuart1 = FreeRTOS_open((const int8_t *)"/LPUART1/", 0);
	uint32_t ulBaudRate = 115200;
	FreeRTOS_ioctl(lpuart1, ioctlSET_SPEED, &ulBaudRate);
	uint32_t ulParity = UART_PARITY_NONE;
	FreeRTOS_ioctl(lpuart1, ioctlSET_UART_PARITY_MODE, &ulParity);
	uint32_t ulStopBits = UART_STOPBITS_1;
	FreeRTOS_ioctl(lpuart1, ioctlSET_UART_NUMBER_OF_STOP_BITS, &ulStopBits);

	FreeRTOS_CLIRegisterCommand( &xTasksCommand );
	FreeRTOS_CLIRegisterCommand( &xClearCommand );
	FreeRTOS_write(lpuart1, "Welcome to FreeRTOS ", 20);
	FreeRTOS_write(lpuart1, tskKERNEL_VERSION_NUMBER, 7);
	FreeRTOS_write(lpuart1, "\n\r", 2);
	FreeRTOS_write(lpuart1, ">>", 2);

	while(1){
			/* This implementation reads a single character at a time.  Wait in the
	        Blocked state until a character is received. */
			FreeRTOS_read(lpuart1, &cRxedChar, 1);

	        if( cRxedChar == '\r' )
	        {
	            /* A newline character was received, so the input command string is
	            complete and can be processed.  Transmit a line separator, just to
	            make the output easier to read. */
	        	FreeRTOS_write(lpuart1, "\n\r", 2);

	            /* The command interpreter is called repeatedly until it returns
	            pdFALSE.  See the "Implementing a command" documentation for an
	            exaplanation of why this is. */
	            do
	            {
	                /* Send the command string to the command interpreter.  Any
	                output generated by the command interpreter will be placed in the
	                pcOutputString buffer. */
	                xMoreDataToFollow = FreeRTOS_CLIProcessCommand
	                              (
	                                  pcInputString,   /* The command string.*/
	                                  pcOutputString,  /* The output buffer. */
	                                  MAX_OUTPUT_LENGTH/* The size of the output buffer. */
	                              );

	                /* Write the output generated by the command interpreter to the
	                console. */
	                FreeRTOS_write(lpuart1, pcOutputString, 0);

	            } while( xMoreDataToFollow != pdFALSE );
                FreeRTOS_write(lpuart1, ">>", 2);

	            /* All the strings generated by the input command have been sent.
	            Processing of the command is complete.  Clear the input string ready
	            to receive the next command. */
	            cInputIndex = 0;
	            memset( pcInputString, 0x00, MAX_INPUT_LENGTH );
	        }
	        else
	        {
	            /* The if() clause performs the processing after a newline character
	            is received.  This else clause performs the processing if any other
	            character is received. */

	            if( cRxedChar == '\n' )
	            {
	                /* Ignore carriage returns. */
	            }
	            //else if( cRxedChar == '\b' )
	            else if( cRxedChar == 0x7F )
	            {
	                /* Backspace was pressed.  Erase the last character in the input
	                buffer - if there are any. */
	                if( cInputIndex > 0 )
	                {
	                    cInputIndex--;
	                    pcInputString[ cInputIndex ] = (char)'\0';
	                    FreeRTOS_write(lpuart1, &cRxedChar, 1);
	                }
	            }
	            else
	            {
	                /* A character was entered.  It was not a new line, backspace
	                or carriage return, so it is accepted as part of the input and
	                placed into the input buffer.  When a \n is entered the complete
	                string will be passed to the command interpreter. */
	                if( cInputIndex < MAX_INPUT_LENGTH )
	                {
	                    pcInputString[ cInputIndex ] = cRxedChar;
	                    cInputIndex++;
	                }
	                FreeRTOS_write(lpuart1, &cRxedChar, 1);
	            }
	        }
	}
}

void echo(void *param){
	uint8_t data;
	uint8_t data_rx;
	HAL_UART_Receive_IT(&hlpuart1, &data, 1);
	while(1){
		receive_uart(&data_rx);
		if (data_rx == '\r'){
			transmite_uart(&data_rx, 1);
			data_rx = '\n';
			transmite_uart(&data_rx, 1);
		}else{
			transmite_uart(&data_rx, 1);
		}
	}
}

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin){
	BaseType_t pxHigherPriorityTaskWoken = pdFALSE;
	HAL_NVIC_DisableIRQ(EXTI15_10_IRQn);
	xTimerStartFromISR(debounce, &pxHigherPriorityTaskWoken);
	portYIELD_FROM_ISR(pxHigherPriorityTaskWoken);
}

volatile uint32_t cnt3 = 0;
static void sobra_cpu(void *param){
	uint32_t teste = 0;
	while(1){
		cnt3++;
		for (int i=0; i<1024;i++){
			teste = teste ^ 0xF3;
		}
	}
}

typedef enum button_codes_t_ {
	BUTTON_1 = 1,
	BUTTON_2,
	BUTTON_3
}button_codes_t;

void debounce_callback( TimerHandle_t xTimer ){
	uint8_t buffer = BUTTON_1;
	xQueueSendToBack(queue_keyb, &buffer, 0);
	HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
}
/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{

  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  /* USER CODE BEGIN 2 */

  /* USER CODE END 2 */

  /* USER CODE BEGIN RTOS_MUTEX */
  /* add mutexes, ... */
  mutex = xSemaphoreCreateMutex();
  /* USER CODE END RTOS_MUTEX */

  /* USER CODE BEGIN RTOS_SEMAPHORES */
  /* add semaphores, ... */
  sem = xSemaphoreCreateBinary();
  //sem_rx = xSemaphoreCreateBinary();
  /* USER CODE END RTOS_SEMAPHORES */

  /* USER CODE BEGIN RTOS_TIMERS */
  /* start timers, add new ones, ... */
  debounce = xTimerCreate("debounce do teclado", 50, pdFALSE, NULL, debounce_callback);
  /* USER CODE END RTOS_TIMERS */

  /* USER CODE BEGIN RTOS_QUEUES */
  /* add queues, ... */
  queue_rx = xQueueCreate(16, sizeof(uint8_t));
  queue_keyb = xQueueCreate(16, sizeof(char));
  /* USER CODE END RTOS_QUEUES */

  /* Create the thread(s) */
  /* definition and creation of defaultTask */
  osThreadDef(defaultTask, StartDefaultTask, osPriorityNormal, 0, 128);
  defaultTaskHandle = osThreadCreate(osThread(defaultTask), NULL);

  /* USER CODE BEGIN RTOS_THREADS */
  /* add threads, ... */
  static led_t led_verde = {LED_GPIO_Port, LED_Pin, 500};
  //led_t led_azul = {LED_GPIO_Port, LED_Pin, 200};
  xTaskCreate(pisca_led, "Tarefa teste", 256, &led_verde, 3, NULL);

  //xTaskCreate(envia_serial_1, "serial 1", 256, NULL, 3, NULL);
  //xTaskCreate(envia_serial_2, "serial 2", 256, NULL, 3, NULL);
  xTaskCreate(shell_task, "shell task", 256, NULL, 4, NULL);
  xTaskCreate(sobra_cpu, "sobra", 256, NULL, 1, NULL);
  /* USER CODE END RTOS_THREADS */

  /* Start scheduler */
  osKernelStart();

  /* We should never get here as control is now taken by the scheduler */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
  }
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1_BOOST);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = RCC_PLLM_DIV6;
  RCC_OscInitStruct.PLL.PLLN = 85;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* USER CODE BEGIN MX_GPIO_Init_1 */

  /* USER CODE END MX_GPIO_Init_1 */

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOF_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(LED_GPIO_Port, LED_Pin, GPIO_PIN_RESET);

  /*Configure GPIO pin : BUTTON_Pin */
  GPIO_InitStruct.Pin = BUTTON_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_IT_RISING;
  GPIO_InitStruct.Pull = GPIO_PULLDOWN;
  HAL_GPIO_Init(BUTTON_GPIO_Port, &GPIO_InitStruct);

  /*Configure GPIO pin : LED_Pin */
  GPIO_InitStruct.Pin = LED_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(LED_GPIO_Port, &GPIO_InitStruct);

  /* EXTI interrupt init*/
  HAL_NVIC_SetPriority(EXTI15_10_IRQn, 5, 0);
  HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);

  /* USER CODE BEGIN MX_GPIO_Init_2 */

  /* USER CODE END MX_GPIO_Init_2 */
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/* USER CODE BEGIN Header_StartDefaultTask */
/**
  * @brief  Function implementing the defaultTask thread.
  * @param  argument: Not used
  * @retval None
  */
/* USER CODE END Header_StartDefaultTask */
void StartDefaultTask(void const * argument)
{
  /* USER CODE BEGIN 5 */
  /* Infinite loop */
  for(;;)
  {
    osDelay(1);
  }
  /* USER CODE END 5 */
}

/**
  * @brief  Period elapsed callback in non blocking mode
  * @note   This function is called  when TIM20 interrupt took place, inside
  * HAL_TIM_IRQHandler(). It makes a direct call to HAL_IncTick() to increment
  * a global variable "uwTick" used as application time base.
  * @param  htim : TIM handle
  * @retval None
  */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
  /* USER CODE BEGIN Callback 0 */
  counter++;
  if (counter >= 1000){
	  counter = 0;
  }
  /* USER CODE END Callback 0 */
  if (htim->Instance == TIM20)
  {
    HAL_IncTick();
  }
  /* USER CODE BEGIN Callback 1 */

  /* USER CODE END Callback 1 */
}

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
